---
tags: [spring-cloud, config server]
projects: [spring-cloud, spring-cloud-config]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-centralized-configuration

本指南将带你了解从建立 http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html[Spring Cloud Config Server]并从中获取配置的过程。

== 你构建什么

你会建立一个配置服务器，然后建立一个客户端在启动的时候获取配置，然后 _refreshes_ 配置而无需重新启动客户端。

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[reveal-gradle]]
[.reveal-gradle]
== Build with Gradle

[[scratch]]
[.use-gradle]
== Build with Gradle

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_both_builds.adoc[]

`configuration-service/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/configuration-service/build.gradle[]
----

`configuration-client/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/configuration-client/build.gradle[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

[[reveal-maven]]
[.reveal-maven]
== Build with Maven

[[use-maven]]
[.use-maven]
== Build with Maven

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro_maven.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

为了快速启动，这里是服务器和客户端应用程序的完整配置：

`configuration-service/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/configuration-service/pom.xml[]
----

`configuration-client/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/configuration-client/pom.xml[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-maven-plugin.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== 启动配置服务器
您首先需要一个配置服务，充当Spring应用程序和典型的版本控制的配置文件存储库之间的中介。你可以用Spring Cloud的 `@EnableConfigServer` 建立一个配置服务器，这样其他应用程序可以与它沟通。这是一个普通的Spring Boot应用，添加了一个注解，为了 _enable_ 配置服务器。

`configuration-service/src/main/java/hello/ConfigServiceApplication.java`
[source,java]
----
include::complete/configuration-service/src/main/java/hello/ConfigServiceApplication.java[]
----

配置服务器需要知道要管理哪个存储库。这里有几种选择，但我们将使用基于Git的文件系统存储库。你也可以将配置服务器指向GitHub或gitlab库。在文件系统上，创建一个新的目录然后在这个目录下运行 `git init` 。然后添加一个名为 `a-bootiful-client.properties` 的文件到Git仓库。确保 `git commit` 提交了它。不久，你将连接到一个Spring Boot应用的配置服务器。它的 `spring.application.name` 属性标志它对配置服务器来说，是一个 `a-bootiful-client` 。这就是配置服务器如何知道要发送给特定客户机的哪一组配置。它 _也_ 将发送任何在git仓库找到的文件名为 `application.properties` 或 `application.yml` 的值。具体命名的文件（如 `a-bootiful-client.properties`）属性键会重写那些 `application.properties` 或 `application.yml` 。

添加一个简单的属性和值, `message = Hello world`, 到刚创建的 `a-bootiful-client.properties` 文件，然后 `git commit` 这些更改.

通过指定 `configuration-service/src/main/resources/application.properties` 文件中的 `spring.cloud.config.server.git.uri` 属性来执行Git仓库的路径。确保在同一台机器上同时运行此服务器和另一个Spring Boot应用程序时，指定一个不同 `server.port` 值，以避免端口冲突。

`configuration-service/src/main/resources/application.properties`
[source,properties]
----
include::complete/configuration-service/src/main/resources/application.properties[]
----


== 使用配置客户端从配置服务器读取配置

现在我们已经建立了一个配置服务器，让我们建立一个新的Spring Boot应用程序,使用配置服务器加载自己的配置，根据需求 _刷新_ 它的配置以反映配置服务器上的的变化，而无需重新启动JVM。为了连接到配置服务器，添加 `org.springframework.cloud:spring-cloud-starter-config` 依赖。Spring会发现配置属性文件，和从 `application.properties` 或 `application.yml` 或任何其他 `PropertySource` 加载的一样。

在 _bootstrap_ 期间，配置客户端的配置属性必须是在从配置服务器读取到其余的应用配置 _之前_ 。将客户端的 `spring.application.name` 的值指定为 `a-bootiful-client` 然后定位 `configuration-client/src/main/resources/bootstrap.properties` 文件中的 `spring.cloud.config.uri` 到配置服务器，它们回避其他任何配置都更早加载。


`configuration-client/src/main/resources/bootstrap.properties`
[source,java]
----
include::complete/configuration-client/src/main/resources/bootstrap.properties[]
----


客户端可以使用畅通方式访问任何配置服务器中的值 (比如 `@ConfigurationProperties`, `@Value("${...}")` 或者 `Environment` 抽象化) .创建一个Spring MVC REST controller，返回已解析的 `message` 属性值。请参考 http://knost.top/guides/gs/rest-service/[Building a RESTful Web Service] 指南了解更多关于使用Spring MVC和Spring Boot构建REST服务的更多信息。 

默认情况下，配置值是在客户机启动时读取的，而不要再次读取。你能强迫一个bean的配置 _refresh_ - 去配置服务器拉取更新了的值 - 通过对` MessageRestController `注解一个 Spring Cloud 配置 `@RefreshScope` 然后通过触发 _refresh_ 事件。

`configuration-client/src/main/java/hello/ConfigClientApplication.java`
[source,java]
----
include::complete/configuration-client/src/main/java/hello/ConfigClientApplication.java[]
----

== 测试你的应用

首先启动配置服务，然后，一旦加载，启动客户端，测试端到端结果。访问在浏览器、客户端应用程序 `http://localhost:8080/message` 。在那里，您应该看到响应中反映的字符串 `Hello world` 。

为在Git仓库中的 `a-bootiful-client.properties` 文件改变 `message` 的键的值（ 比如 `Hello Spring!`）。你能通过访问 `http://localhost:8888/a-bootiful-client/default` 来确认配置服务器上的变化。为了强制客户端刷新自己，你需要调用刷新 Spring Boot Actuator的端点， Spring Boot的 Actuator  公开了操作端点，如关于应用程序的健康检查和环境信息。为了使用它，你必须添加 `org.springframework.boot:spring-boot-starter-actuator` 到客户端应用程序的类路径。你可以调用 `refresh` Actuator端点发送一个空的HTTP `后`到客户端的`刷新`端点，`http://localhost:8080/refresh` ，然后通过检查 `http://localhost:8080/message` 端点确认它的工作。

NOTE: 我们在客户机应用程序中设置了 `management.security.enabled=false` ，使之易于测试（默认情况下，从Spring Boot 1.5开始，执行器端点是默认安全的）。默认情况下，如果你不设置标志,你仍然可以通过JMX访问他们。


== 总结
祝贺你!您刚刚使用Spring来为所有服务集中配置，首先是建立，然后动态更新配置。

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]
